language: python
python:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
  - '3.13'
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
install:
  - pip install -Ue .[tests]
script: pytest --cov=tc_prometheus tests/ --cov-report term-missing
